# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 08:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255, null=True)),
                ('datetaken', models.CharField(max_length=255, null=True)),
                ('dateupload', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('latitude_rnd', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude_rnd', models.DecimalField(decimal_places=10, max_digits=15)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
