# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_mushroomspot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
    ]
