# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
