# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='page_url',
            field=models.URLField(null=True),
        ),
    ]
